version: '3.9'

services:

  # postgres
  envs_test_database:
    image: postgres:alpine
    container_name: envs_test_database
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}